applicationId: 'YOUR-APPLICATIONID-HERE' # it MUST be a quoted string. Snowflakes exceed 2^53.
botToken: 'YOUR-BOT-TOKEN-HERE'
workingDirectoryPathBase: '/whatever/graci-working'
musicDirectoryPath: '/whatever/graci-music'

guildIdsForApplicationCommands: # these MUST be quoted strings. Snowflakes exceed 2^53.
  - '12345678'
  - '87654321'

# I haven't published the source for this yet. the expected behavior when run:
# - accepts two arguments:
#     1. a path to a directory where the files should be saved.
#     2. a fixed number of milliseconds to add to the start.
# - then it will create files in that directory named like "screen.N.mkv", where N is an arbitrary
#   number of milliseconds since the start (with that fixed number added).
# - it will create more than one if the thing being recorded gets resized partway through, ensuring
#   that each file only has frames of a given size.
# - the intended way to get it to stop doing this is to send SIGINT, though for whatever reason, I
#   can't easily get it to return an exit code of 0 when this happens instead of 130, so thank you
#   for playing Wing Commander, I guess.
recordScreenExe: '/whatever/path/to/secret/exe/that/i/havent/published/yet'
ffmpegPulseAudioInput: 'alsa_output.YOU_GOT_THIS_I_BELIEVE_IN_YOU.analog-stereo.monitor'

usernameTitleMappings:
  - 'Whoever#1234': 'MyFriendWhoever'
