applicationId: 'YOUR-APPLICATIONID-HERE' # it MUST be a quoted string. Snowflakes exceed 2^53.
botToken: 'YOUR-BOT-TOKEN-HERE'
workingDirectoryPathBase: '/whatever/graci-working'
musicDirectoryPath: '/whatever/graci-music'

guildIdsForApplicationCommands: # these MUST be quoted strings. Snowflakes exceed 2^53.
  - '12345678'
  - '87654321'

# I haven't published the source for this yet. the expected behavior when run:
# - accepts one argument: a path to a file that doesn't exist (yet) in a directory that does.
# - very early on, it creates a file at that path (mkfifo) and opens it for writing.
# - very soon after, it starts writing a stream of frames of 2560x1440 BGRx pixels to the fifo.
# - the intended way to get it to stop doing this is to send SIGINT, though for whatever reason, I
#   can't easily get it to return an exit code of 0 when this happens instead of 130, so thank you
#   for playing Wing Commander, I guess.
recordScreenExe: '/whatever/path/to/secret/exe/that/i/havent/published/yet'

ffmpegPulseAudioInputs:
  - 'alsa_output.YOU_GOT_THIS_I_BELIEVE_IN_YOU.analog-stereo.monitor'

usernameTitleMappings:
  - 'Whoever#1234': 'MyFriendWhoever'
