bot_token: 'YOUR-BOT-TOKEN-HERE'
working_directory_path_base: '/whatever/graci-working'
music_directory_path: '/whatever/graci-music'

guild_ids_for_application_commands:
	- 12345678
	- 87654321

username_title_mappings:
	- 'Whoever#1234': 'MyFriendWhoever'

ffmpeg_args:
	desktop_audio_inputs:
		'alsa_output.YOU_GOT_THIS_I_BELIEVE_IN_YOU.analog-stereo.monitor':
			- '-use_wallclock_as_timestamps': '1'
			- '-f': 'pulse'
			- '-ar': '48000'
			- '-ac': '2'
			- '-thread_queue_size': '4096'
			- '-threads': '0'

	realtime_audio_encode:
		- '-c': 'flac'

	offline_audio_encode:
		- '-c': 'flac'
		- '-compression_level': '12'

	realtime_video_encode:
		- '-c': 'libx264rgb'
		- '-crf': '0'
		- '-filter': 'fps=60'
		- '-preset': 'ultrafast'
		- '-tune': 'zerolatency'

	offline_video_encode:
		- '-c': 'libsvtav1'
		- '-preset': '5'
		- '-crf': '24'
		- '-pix_fmt': 'yuv420p10le'
		- '-svtav1-params': 'tune=0'
